services:
  nodejs-server:
    image: harshdotexe/chaicode-cicd
    deploy:
      replicas: 5
    networks:
      - cicd-internal # same network no need to expose
  caddy:
    image: caddy:latest
    volumes: 
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - cicd-internal


networks:
  cicd-internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: