name: Deploy NodeJS code on Excloud - v1 - Traditional

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 # code ka access milega
            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Qemu
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Docker Build and Push
              run: |
                  docker build -t harshdotexe/chaicode-cicd .
                  docker push harshdotexe/chaicode-cicd

            - name: Deploy on ExCloud
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }} # your ip
                  username: ubuntu
                  key: ${{ secrets.PRIVATE_KEY }} # from github lelo
                  script: |
                      sudo docker stop chaicode-cicd || true

                      sudo docker rm chaicode-cicd || true

                      sudo docker pull harshdotexe/chaicode-cicd

                      sudo docker run -d --name chaicode-cicd -p 80:8000 harshdotexe/chaicode-cicd:latest

                      sudo docker image prune -f